version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    versioning-strategy: "increase-if-necessary"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
